services:
  back:
    build: .
    container_name: back
    command: python3 manage.py runserver 0.0.0.0:9000
    volumes:
      - ./core:/app
    ports:
      - "9000:9000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True  

 